# Generated by Django 5.2.6 on 2025-09-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientfile',
            name='patient_email',
        ),
        migrations.AddField(
            model_name='patientfile',
            name='access_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='disease',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='patientfile',
            name='patient_id',
            field=models.CharField(default='UnknownID', max_length=50),
        ),
    ]
