# Generated by Django 5.2.6 on 2025-09-27 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patientfile_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('management', 'Management')], default='doctor', max_length=15),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(blank=True, default='', max_length=50)),
                ('medical_history', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('lab_results', models.TextField(blank=True, default='')),
                ('imaging_reports', models.TextField(blank=True, default='')),
                ('prescriptions', models.TextField(blank=True, default='')),
                ('immunizations', models.TextField(blank=True, default='')),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('insurance_details', models.TextField(blank=True, default='')),
                ('payment_info', models.TextField(blank=True, default='')),
                ('bank_account', models.CharField(blank=True, default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='patient_pdfs/')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('access_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
